name: Build ESP8266 Binary

on:
  push:
    paths:
      - '**/*.ino'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Compile for NodeMCU
      uses: arduino/compile-sketches@v1
      with:
        fqbn: esp8266:esp8266:nodemcuv2
        platforms: |
          - name: esp8266:esp8266
            source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        sketch-paths: |
          - .